In [2]:
import numpy as np

### 多维数组的运算

In [3]:
A = np.array([1,2,3,4])
print(A)
np.ndim(A)
A.shape
A.shape[0]

[1 2 3 4]


4

In [4]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(np.ndim(B)) # ndim是获取数组的维度
print(B.shape) # shape是获取数组的形状

A = np.array([1,2,3,4])
print(A)
print(np.ndim(A))
print(A.shape)

C = np.array([[1,2],[3,4]])
print(C)
print(np.ndim(C))
print(C.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
[1 2 3 4]
1
(4,)
[[1 2]
 [3 4]]
2
(2, 2)


#### 矩阵乘法

In [ ]:
A = np.array([[1,2], [3,4]])
print(A.shape)
B = np.array([[5,6], [7,8]])
r1 = np.dot(A, B) # A的行依次乘以B的列的和作为结果矩阵的元素。
r2 = np.dot(B, A)
print(r1)
print(r2) # r1与r2不同，即两个矩阵的点积顺序不同，结果也就不同。

(2, 2)
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [12]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
r3 = np.dot(A, B)
r4 = np.dot(B, A)
print(r3)
print(r4)

[[22 28]
 [49 64]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


> 矩阵乘法需要满足A矩阵(n, m)且B矩阵(m, k)，结果为形状为(n, k)的矩阵。如果A和B都是(n, n)，A * B 和 B * A是不同的。
>由于矩阵的乘法规则是A矩阵的行乘以B矩阵的列之和，产生新矩阵的元素。因此，A矩阵的第1维元素个数应该与B矩阵的第0维元素个数相同, 否则会报错。

In [13]:
C = np.array([[1,2],[3,4]])
r5 = np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

> 在矩阵的乘积运算中，对应维度的元素个数要保持一致。
> 另外，当A是二维矩阵，B是一维矩阵时，对应维度的元素个数要保持一致的原则依然成立。

In [14]:
A = np.array([[1,2],[3,4],[5,6]])
print(A.shape)
B = np.array([7,8])
print(B.shape)
r6 = np.dot(A, B)
# r7 = np.dot(B, A)
print(r6)
# print(r7)

(3, 2)
(2,)
[23 53 83]
