In [1]:
import numpy as np

In [2]:
x=np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [4]:
y=np.array([2.0,4.0,6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x/2.0)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


In [6]:
A=np.array([[1,2],[3,4]])
print(A)
print(A.shape, A.dtype)

[[1 2]
 [3 4]]
(2, 2) int32


In [8]:
B=np.array([[3,0],[0,6]])
print(A+B)
print(A*B)
print(A*20)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
[[20 40]
 [60 80]]


In [9]:
C=np.array([10,20])
print(A*C)

[[10 40]
 [30 80]]


In [10]:
for row in A:
    print(row)

[1 2]
[3 4]


In [12]:
X=A.flatten()
print(X)
Y=X[np.array([0,2])]
print(Y)

[1 2 3 4]
[1 3]


In [13]:
print(A>2)
print(X[X>2])

[[False False]
 [ True  True]]
[3 4]
